package com.keeps.model;

// default package
// Generated 2017-4-7 13:47:46 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * SzlGoodsToTag generated by hbm2java
 */
@Entity
@Table(name = "szl_goods_to_tag")
public class SzlGoodsToTag extends AbstractModelInteger implements ModelPlusSchool {

	private Integer id;
	private Integer tagid;
	private Integer goodsid;

	private Date createtime;
	private Date updatetime;
	private Integer createperson;
	
	public SzlGoodsToTag() {
	}

	public SzlGoodsToTag(Integer tagid, Integer goodsid) {
		this.tagid = tagid;
		this.goodsid = goodsid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tagid")
	public Integer getTagid() {
		return this.tagid;
	}

	public void setTagid(Integer tagid) {
		this.tagid = tagid;
	}

	@Column(name = "goodsid")
	public Integer getGoodsid() {
		return this.goodsid;
	}

	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	@Transient
	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Transient
	public Date getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Transient
	public Integer getCreateperson() {
		return createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
