package com.keeps.model;

// default package
// Generated 2017-4-5 23:10:06 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModel;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * SzlGoods generated by hbm2java
 */
@Entity
@Table(name = "szl_goods")
public class SzlGoods extends AbstractModel implements ModelPlusSchool{

	private Integer id;
	private Integer classid;
	private String goodsname;
	private String goodsimage;
	private Float originalprice;
	private Float currentprice;
	private Float couponafterprice;
	private Float couponprice;
	private Date starttime;
	private Date endtime;
	private Integer tocouponnum;
	private String goodstag;
	private Integer goodssource;
	private Integer ishot;
	private Integer isrecommend;
	private Integer isdelete;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	private String viewgoodsImage;
	private String className;

	public SzlGoods() {
	}

	public SzlGoods(Integer id, Integer classid, String goodsname, String goodsimage, Float currentprice,
			Float couponafterprice, Float couponprice, Date starttime, Date endtime, Integer tocouponnum, String goodstag,
			Integer goodssource, Date createtime, Date updatetime, Integer createperson) {
		this.id = id;
		this.classid = classid;
		this.goodsname = goodsname;
		this.goodsimage = goodsimage;
		this.currentprice = currentprice;
		this.couponafterprice = couponafterprice;
		this.couponprice = couponprice;
		this.starttime = starttime;
		this.endtime = endtime;
		this.tocouponnum = tocouponnum;
		this.goodstag = goodstag;
		this.goodssource = goodssource;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}
	public SzlGoods(Integer id, Integer classid, String goodsname, String goodsimage, Float originalprice,
			Float currentprice, Float couponafterprice, Float couponprice, Date starttime, Date endtime, Integer tocouponnum,
			String goodstag, Integer goodssource, Integer ishot, Integer isrecommend, Integer isdelete, Date createtime,
			Date updatetime, Integer createperson) {
		this.id = id;
		this.classid = classid;
		this.goodsname = goodsname;
		this.goodsimage = goodsimage;
		this.originalprice = originalprice;
		this.currentprice = currentprice;
		this.couponafterprice = couponafterprice;
		this.starttime = starttime;
		this.endtime = endtime;
		this.tocouponnum = tocouponnum;
		this.goodstag = goodstag;
		this.goodssource = goodssource;
		this.ishot = ishot;
		this.isrecommend = isrecommend;
		this.isdelete = isdelete;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "classid", nullable = false)
	public Integer getClassid() {
		return this.classid;
	}

	public void setClassid(Integer classid) {
		this.classid = classid;
	}

	@Column(name = "goodsname", nullable = false)
	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	@Column(name = "goodsimage", nullable = false, length = 40)
	public String getGoodsimage() {
		return this.goodsimage;
	}

	public void setGoodsimage(String goodsimage) {
		this.goodsimage = goodsimage;
	}

	@Column(name = "originalprice", precision = 10, scale = 0)
	public Float getOriginalprice() {
		return this.originalprice;
	}

	public void setOriginalprice(Float originalprice) {
		this.originalprice = originalprice;
	}

	@Column(name = "currentprice", nullable = false, precision = 10, scale = 0)
	public Float getCurrentprice() {
		return this.currentprice;
	}

	public void setCurrentprice(Float currentprice) {
		this.currentprice = currentprice;
	}

	@Column(name = "couponafterprice", nullable = false, precision = 10, scale = 0)
	public Float getCouponafterprice() {
		return this.couponafterprice;
	}

	public void setCouponafterprice(Float couponafterprice) {
		this.couponafterprice = couponafterprice;
	}

	@Column(name = "couponprice", nullable = false, precision = 10, scale = 0)
	public Float getCouponprice() {
		return this.couponprice;
	}

	public void setCouponprice(Float couponprice) {
		this.couponprice = couponprice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starttime", nullable = false, length = 19)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endtime", nullable = false, length = 19)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "tocouponnum", nullable = false)
	public Integer getTocouponnum() {
		return this.tocouponnum;
	}

	public void setTocouponnum(Integer tocouponnum) {
		this.tocouponnum = tocouponnum;
	}

	@Column(name = "goodstag", nullable = false)
	public String getGoodstag() {
		return this.goodstag;
	}

	public void setGoodstag(String goodstag) {
		this.goodstag = goodstag;
	}

	@Column(name = "goodssource", nullable = false)
	public Integer getGoodssource() {
		return this.goodssource;
	}

	public void setGoodssource(Integer goodssource) {
		this.goodssource = goodssource;
	}

	@Column(name = "ishot")
	public Integer getIshot() {
		return this.ishot;
	}

	public void setIshot(Integer ishot) {
		this.ishot = ishot;
	}

	@Column(name = "isrecommend")
	public Integer getIsrecommend() {
		return this.isrecommend;
	}

	public void setIsrecommend(Integer isrecommend) {
		this.isrecommend = isrecommend;
	}

	@Column(name = "isdelete")
	public Integer getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", nullable = false, length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson", nullable = false)
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

	@Transient
	public String getViewgoodsImage() {
		return viewgoodsImage;
	}

	public void setViewgoodsImage(String viewgoodsImage) {
		this.viewgoodsImage = viewgoodsImage;
	}

	@Transient
	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

}
