package com.keeps.model;

// default package
// Generated 2017-4-5 23:20:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.keeps.core.model.AbstractModel;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * SzlGoodsClass generated by hbm2java
 */
@Entity
@Table(name = "szl_goods_class")
public class SzlGoodsClass  extends AbstractModel implements ModelPlusSchool{

	private Integer id;
	private Integer pid;
	private String classicon;
	private String classname;
	private Integer ishot;
	private Integer isrecommend;
	private Integer classsort;
	private String classsettle;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	public SzlGoodsClass() {
	}

	public SzlGoodsClass(Integer pid, String classicon, String classname, Integer ishot, Integer isrecommend, Integer classsort,
			Date createtime, Date updatetime, Integer createperson) {
		this.pid = pid;
		this.classicon = classicon;
		this.classname = classname;
		this.ishot = ishot;
		this.isrecommend = isrecommend;
		this.classsort = classsort;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	public SzlGoodsClass(Integer pid, String classicon, String classname, Integer ishot, Integer isrecommend, Integer classsort,
			String classsettle, Date createtime, Date updatetime, Integer createperson) {
		this.pid = pid;
		this.classicon = classicon;
		this.classname = classname;
		this.ishot = ishot;
		this.isrecommend = isrecommend;
		this.classsort = classsort;
		this.classsettle = classsettle;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pid", nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "classicon", nullable = false)
	public String getClassicon() {
		return this.classicon;
	}

	public void setClassicon(String classicon) {
		this.classicon = classicon;
	}

	@Column(name = "classname", nullable = false)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	@Column(name = "ishot", nullable = false)
	public Integer getIshot() {
		return this.ishot;
	}

	public void setIshot(Integer ishot) {
		this.ishot = ishot;
	}

	@Column(name = "isrecommend", nullable = false)
	public Integer getIsrecommend() {
		return this.isrecommend;
	}

	public void setIsrecommend(Integer isrecommend) {
		this.isrecommend = isrecommend;
	}

	@Column(name = "classsort", nullable = false)
	public Integer getClasssort() {
		return this.classsort;
	}

	public void setClasssort(Integer classsort) {
		this.classsort = classsort;
	}

	@Column(name = "classsettle")
	public String getClasssettle() {
		return this.classsettle;
	}

	public void setClasssettle(String classsettle) {
		this.classsettle = classsettle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", nullable = false, length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson", nullable = false)
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
