package com.keeps.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 2017-4-7 13:47:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * SzlTag generated by hbm2java
 */
@Entity
@Table(name = "szl_tag")
public class SzlTag extends AbstractModelInteger implements ModelPlusSchool {

	private Integer id;
	private String tagname;
	private Integer ishot;
	private Integer clicknum;
	private Integer goodsnum;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	public SzlTag() {
	}

	public SzlTag(Integer id, String tagname, Integer ishot, Integer clicknum, Integer goodsnum, Date createtime, Date updatetime,
			Integer createperson) {
		this.id = id;
		this.tagname = tagname;
		this.ishot = ishot;
		this.clicknum = clicknum;
		this.goodsnum = goodsnum;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tagname", nullable = false)
	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

	@Column(name = "ishot", nullable = false)
	public Integer getIshot() {
		return this.ishot;
	}

	public void setIshot(Integer ishot) {
		this.ishot = ishot;
	}

	@Column(name = "clicknum", nullable = false)
	public Integer getClicknum() {
		return this.clicknum;
	}

	public void setClicknum(Integer clicknum) {
		this.clicknum = clicknum;
	}

	@Column(name = "goodsnum", nullable = false)
	public Integer getGoodsnum() {
		return this.goodsnum;
	}

	public void setGoodsnum(Integer goodsnum) {
		this.goodsnum = goodsnum;
	}

	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", nullable = false, length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson", nullable = false)
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
