package com.keeps.model;
// default package
// Generated 2017-4-12 16:33:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TAdv generated by hbm2java
 */
@Entity
@Table(name = "t_adv")
public class TAdv extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private Integer apId;
	private String advTitle;
	private String advLink;
	private String advContent;
	private Integer isShow;
	private String starttime;
	private String endtime;
	private Integer slideSort;
	private Integer clickNum;
	private Float advPrice;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;
	
	private String advContentpath;//图片内容
	private Integer apClass;
	private String apName;
	private Integer apDisplay;
	private Integer advNum;
	private Integer countnum;

	public TAdv() {
	}


	public TAdv(Integer apId, String advTitle, String advLink, String advContent, Integer isShow, String starttime,
			String endtime, Integer slideSort, Integer clickNum, Float advPrice, Date createtime, Date updatetime, Integer createperson) {
		this.apId = apId;
		this.advTitle = advTitle;
		this.advLink = advLink;
		this.advContent = advContent;
		this.isShow = isShow;
		this.starttime = starttime;
		this.endtime = endtime;
		this.slideSort = slideSort;
		this.clickNum = clickNum;
		this.advPrice = advPrice;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ap_id", nullable = false)
	public Integer getApId() {
		return this.apId;
	}

	public void setApId(Integer apId) {
		this.apId = apId;
	}

	@Column(name = "adv_title")
	public String getAdvTitle() {
		return this.advTitle;
	}

	public void setAdvTitle(String advTitle) {
		this.advTitle = advTitle;
	}

	@Column(name = "adv_link", nullable = false, length = 100)
	public String getAdvLink() {
		return this.advLink;
	}

	public void setAdvLink(String advLink) {
		this.advLink = advLink;
	}

	@Column(name = "adv_content", length = 1000)
	public String getAdvContent() {
		return this.advContent;
	}

	public void setAdvContent(String advContent) {
		this.advContent = advContent;
	}

	@Column(name = "is_show", nullable = false)
	public Integer getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	@Column(name = "starttime", nullable = false, length = 19)
	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	@Column(name = "endtime", nullable = false, length = 19)
	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	@Column(name = "slide_sort", nullable = false)
	public Integer getSlideSort() {
		return this.slideSort;
	}

	public void setSlideSort(Integer slideSort) {
		this.slideSort = slideSort;
	}

	@Column(name = "click_num", nullable = false)
	public Integer getClickNum() {
		return this.clickNum;
	}

	public void setClickNum(Integer clickNum) {
		this.clickNum = clickNum;
	}

	@Column(name = "adv_price", nullable = false, precision = 10, scale = 2)
	public Float getAdvPrice() {
		return this.advPrice;
	}

	public void setAdvPrice(Float advPrice) {
		this.advPrice = advPrice;
	}


	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

	@Transient
	public Integer getApClass() {
		return apClass;
	}


	public void setApClass(Integer apClass) {
		this.apClass = apClass;
	}

	@Transient
	public String getApName() {
		return apName;
	}


	public void setApName(String apName) {
		this.apName = apName;
	}

	@Transient
	public Integer getApDisplay() {
		return apDisplay;
	}


	public void setApDisplay(Integer apDisplay) {
		this.apDisplay = apDisplay;
	}


	@Transient
	public String getAdvContentpath() {
		return advContentpath;
	}


	public void setAdvContentpath(String advContentpath) {
		this.advContentpath = advContentpath;
	}


	@Transient
	public Integer getAdvNum() {
		return advNum;
	}


	public void setAdvNum(Integer advNum) {
		this.advNum = advNum;
	}

	@Transient
	public Integer getCountnum() {
		return countnum;
	}


	public void setCountnum(Integer countnum) {
		this.countnum = countnum;
	}
	
	
	
}
