package com.keeps.model;
// default package
// Generated 2017-1-18 17:05:55 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.keeps.core.model.AbstractModel;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TArticleType generated by hbm2java
 */
@Entity
@Table(name = "t_article_type")
public class TArticleType extends AbstractModel implements ModelPlusSchool {

	private Integer id;
	private String name;
	private Integer pid;
	private Integer dictid;
	private String url;
	private Integer isshow;
	private Integer sort;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	public TArticleType() {
	}

	public TArticleType(Integer id) {
		this.id = id;
	}

	public TArticleType(Integer id, String name, Integer pid, Integer dictid, String url, Integer isshow, Integer sort,
			Date createtime, Date updatetime, Integer createperson) {
		this.id = id;
		this.name = name;
		this.pid = pid;
		this.dictid = dictid;
		this.url = url;
		this.isshow = isshow;
		this.sort = sort;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pid")
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "dictid")
	public Integer getDictid() {
		return this.dictid;
	}

	public void setDictid(Integer dictid) {
		this.dictid = dictid;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "isshow")
	public Integer getIsshow() {
		return this.isshow;
	}

	public void setIsshow(Integer isshow) {
		this.isshow = isshow;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
