package com.keeps.model;

// default package
// Generated 2017-6-20 21:33:10 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TClient generated by hbm2java
 */
@Entity
@Table(name = "t_client")
public class TClient extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private String name;
	private Integer sex;
	private String phone;
	private String landline;
	private String email;
	private Integer type;
	private Integer attention;
	private String birthdate;
	private String buycommodity;
	private String hobbycommodity;
	private Integer receivetype;
	private Integer receiveid;
	private String solarbirthdate;
	private Integer islunar;
	private String address;
	private String birthplace;
	private String pym;
	private String allpym;
	private String remark;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;
	private Integer status;
	private Integer isopen;
	
	private Integer recordnum;
	private Integer buynum;
	private String linkempname;
	private String content;
	private String nexttime;
	private String contacttime;
	private String attentionname;
	private String attentionvalue;
	private String typename;
	
	private String fzempid;
	private String fzempname;
	private String receivename;
	private String receivetypename;

	
	private String createtimesta;
	private String createtimeend;
	private String contacttimesta;
	private String contacttimeend;
	private String buytimesta;
	private String buytimeend;
	private String nextcontacttimesta;
	private String nextcontacttimeend;
	public TClient() {
	}

	public TClient(String name, String phone) {
		this.name = name;
		this.phone = phone;
	}

	public TClient(String name, Integer sex, String phone, String landline, String email, Integer type,
			Integer attention, String birthdate, String buycommodity, String hobbycommodity, Integer receiveid,
			String solarbirthdate, Integer islunar, String address, String birthplace, String pym, String allpym,
			String remark, Date createtime, Date updatetime, Integer createperson) {
		this.name = name;
		this.sex = sex;
		this.phone = phone;
		this.landline = landline;
		this.email = email;
		this.type = type;
		this.attention = attention;
		this.birthdate = birthdate;
		this.buycommodity = buycommodity;
		this.hobbycommodity = hobbycommodity;
		this.receiveid = receiveid;
		this.solarbirthdate = solarbirthdate;
		this.islunar = islunar;
		this.address = address;
		this.birthplace = birthplace;
		this.pym = pym;
		this.allpym = allpym;
		this.remark = remark;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "landline", length = 50)
	public String getLandline() {
		return this.landline;
	}

	public void setLandline(String landline) {
		this.landline = landline;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "attention")
	public Integer getAttention() {
		return this.attention;
	}

	public void setAttention(Integer attention) {
		this.attention = attention;
	}

	@Column(name = "birthdate", length = 19)
	public String getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "buycommodity", length = 1255)
	public String getBuycommodity() {
		return this.buycommodity;
	}

	public void setBuycommodity(String buycommodity) {
		this.buycommodity = buycommodity;
	}

	@Column(name = "hobbycommodity", length = 1255)
	public String getHobbycommodity() {
		return this.hobbycommodity;
	}

	public void setHobbycommodity(String hobbycommodity) {
		this.hobbycommodity = hobbycommodity;
	}

	@Column(name = "receivetype")
	public Integer getReceivetype() {
		return receivetype;
	}

	public void setReceivetype(Integer receivetype) {
		this.receivetype = receivetype;
	}

	@Column(name = "receiveid")
	public Integer getReceiveid() {
		return this.receiveid;
	}

	public void setReceiveid(Integer receiveid) {
		this.receiveid = receiveid;
	}

	@Column(name = "solarbirthdate", length = 19)
	public String getSolarbirthdate() {
		return this.solarbirthdate;
	}

	public void setSolarbirthdate(String solarbirthdate) {
		this.solarbirthdate = solarbirthdate;
	}

	@Column(name = "islunar")
	public Integer getIslunar() {
		return this.islunar;
	}

	public void setIslunar(Integer islunar) {
		this.islunar = islunar;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "birthplace")
	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	@Column(name = "pym", length = 50)
	public String getPym() {
		return this.pym;
	}

	public void setPym(String pym) {
		this.pym = pym;
	}

	@Column(name = "allpym", length = 50)
	public String getAllpym() {
		return this.allpym;
	}

	public void setAllpym(String allpym) {
		this.allpym = allpym;
	}

	@Column(name = "remark", length = 1255)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	@Column(name = "isopen")
	public Integer getIsopen() {
		return isopen;
	}

	public void setIsopen(Integer isopen) {
		this.isopen = isopen;
	}

	@Transient
	public String getLinkempname() {
		return linkempname;
	}

	public void setLinkempname(String linkempname) {
		this.linkempname = linkempname;
	}
	
	@Transient
	public String getContent() {
		return content;
	}


	public void setContent(String content) {
		this.content = content;
	}

	@Transient
	public String getNexttime() {
		return nexttime;
	}

	public void setNexttime(String nexttime) {
		this.nexttime = nexttime;
	}

	@Transient
	public String getContacttime() {
		return contacttime;
	}

	public void setContacttime(String contacttime) {
		this.contacttime = contacttime;
	}

	@Transient
	public String getAttentionname() {
		return attentionname;
	}

	public void setAttentionname(String attentionname) {
		this.attentionname = attentionname;
	}

	@Transient
	public String getAttentionvalue() {
		return attentionvalue;
	}

	public void setAttentionvalue(String attentionvalue) {
		this.attentionvalue = attentionvalue;
	}

	@Transient
	public String getTypename() {
		return typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}
	@Transient
	public String getFzempname() {
		return fzempname;
	}

	public void setFzempname(String fzempname) {
		this.fzempname = fzempname;
	}

	@Transient
	public String getFzempid() {
		return fzempid;
	}

	public void setFzempid(String fzempid) {
		this.fzempid = fzempid;
	}

	@Transient
	public String getReceivename() {
		return receivename;
	}

	public void setReceivename(String receivename) {
		this.receivename = receivename;
	}

	@Transient
	public String getReceivetypename() {
		return receivetypename;
	}

	public void setReceivetypename(String receivetypename) {
		this.receivetypename = receivetypename;
	}

	@Transient
	public Integer getRecordnum() {
		return recordnum;
	}

	public void setRecordnum(Integer recordnum) {
		this.recordnum = recordnum;
	}

	@Transient
	public Integer getBuynum() {
		return buynum;
	}

	public void setBuynum(Integer buynum) {
		this.buynum = buynum;
	}
	

	@Transient
	public String getCreatetimesta() {
		return createtimesta;
	}

	public void setCreatetimesta(String createtimesta) {
		this.createtimesta = createtimesta;
	}

	@Transient
	public String getCreatetimeend() {
		return createtimeend;
	}

	public void setCreatetimeend(String createtimeend) {
		this.createtimeend = createtimeend;
	}

	@Transient
	public String getContacttimesta() {
		return contacttimesta;
	}

	public void setContacttimesta(String contacttimesta) {
		this.contacttimesta = contacttimesta;
	}

	@Transient
	public String getContacttimeend() {
		return contacttimeend;
	}

	public void setContacttimeend(String contacttimeend) {
		this.contacttimeend = contacttimeend;
	}

	@Transient
	public String getBuytimesta() {
		return buytimesta;
	}

	public void setBuytimesta(String buytimesta) {
		this.buytimesta = buytimesta;
	}

	@Transient
	public String getBuytimeend() {
		return buytimeend;
	}

	public void setBuytimeend(String buytimeend) {
		this.buytimeend = buytimeend;
	}

	@Transient
	public String getNextcontacttimesta() {
		return nextcontacttimesta;
	}

	public void setNextcontacttimesta(String nextcontacttimesta) {
		this.nextcontacttimesta = nextcontacttimesta;
	}

	@Transient
	public String getNextcontacttimeend() {
		return nextcontacttimeend;
	}

	public void setNextcontacttimeend(String nextcontacttimeend) {
		this.nextcontacttimeend = nextcontacttimeend;
	}

	

}
