package com.keeps.model;

// default package
// Generated 2017-6-20 21:33:10 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.keeps.core.model.AbstractModelInteger;

/**
 * TDictType generated by hbm2java
 */
@Entity
@Table(name = "t_dict_type")
public class TDictType extends AbstractModelInteger implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String code;
	private Integer pid;
	private String fullpid;
	private String pname;
	private Integer status;
	private Integer sort;
	private Integer fixed;
	private String valuetype;
	private String description;
	private Integer isinsertdict;
	
	public TDictType() {
	}

	public TDictType(String name, String code, Integer pid, String fullpid,Integer status, Integer sort, Integer fixed,String valuetype,String description,Integer isinsertdict) {
		this.name = name;
		this.code = code;
		this.pid = pid;
		this.fullpid = fullpid;
		this.status = status;
		this.sort = sort;
		this.fixed = fixed;
		this.valuetype = valuetype;
		this.description = description;
		this.isinsertdict = isinsertdict;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "pid", nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "fullpid", nullable = false)
	public String getFullpid() {
		return fullpid;
	}

	public void setFullpid(String fullpid) {
		this.fullpid = fullpid;
	}

	@Column(name = "status", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "sort", nullable = false)
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "fixed", nullable = false)
	public Integer getFixed() {
		return this.fixed;
	}

	public void setFixed(Integer fixed) {
		this.fixed = fixed;
	}

	@Column(name = "valuetype", nullable = false)
	public String getValuetype() {
		return valuetype;
	}

	public void setValuetype(String valuetype) {
		this.valuetype = valuetype;
	}

	@Column(name = "description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "isinsertdict")
	public Integer getIsinsertdict() {
		return isinsertdict;
	}

	public void setIsinsertdict(Integer isinsertdict) {
		this.isinsertdict = isinsertdict;
	}

	@Column(name = "pname")
	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

}
