package com.keeps.model;
// default package
// Generated 2017-1-18 17:05:55 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.keeps.core.model.AbstractModel;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TDict generated by hbm2java
 */
@Entity
@Table(name = "t_dict")
public class TDict extends AbstractModel implements ModelPlusSchool {

	private Integer id;
	private Integer dicttypeid;
	private Integer isinternal;
	private String key;
	private String value;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	public TDict() {
	}

	public TDict(Integer id) {
		this.id = id;
	}

	public TDict(Integer id, Integer dicttypeid, Integer isinternal, String key, String value, Date createtime,
			Date updatetime, Integer createperson) {
		this.id = id;
		this.dicttypeid = dicttypeid;
		this.isinternal = isinternal;
		this.key = key;
		this.value = value;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dicttypeid")
	public Integer getDicttypeid() {
		return this.dicttypeid;
	}

	public void setDicttypeid(Integer dicttypeid) {
		this.dicttypeid = dicttypeid;
	}

	@Column(name = "isinternal")
	public Integer getIsinternal() {
		return this.isinternal;
	}

	public void setIsinternal(Integer isinternal) {
		this.isinternal = isinternal;
	}

	@Column(name = "key")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
