package com.keeps.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 2017-6-20 21:33:10 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;

/**
 * TDict generated by hbm2java
 */
@Entity
@Table(name = "t_dict")
public class TDict extends AbstractModelInteger implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer typeid;
	private String typecode;
	private String name;
	private String value;
	private Integer status;
	private Integer sort;
	private Integer fixed;
	
	
	private String typename;

	public TDict() {
	}

	public TDict(Integer id, Integer typeid, String typecode, String name, String value, Integer status, Integer sort, Integer fixed) {
		this.id = id;
		this.typeid = typeid;
		this.typecode = typecode;
		this.name = name;
		this.value = value;
		this.status = status;
		this.sort = sort;
		this.fixed = fixed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "typeid", nullable = false)
	public Integer getTypeid() {
		return typeid;
	}

	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	@Column(name = "typecode", nullable = false)
	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "status", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "sort", nullable = false)
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "fixed", nullable = false)
	public Integer getFixed() {
		return this.fixed;
	}

	public void setFixed(Integer fixed) {
		this.fixed = fixed;
	}

	@Transient
	public String getTypename() {
		return typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

}
