package com.keeps.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 2017-6-19 15:56:01 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TEmprole generated by hbm2java
 */
@Entity
@Table(name = "t_emprole")
public class TEmprole extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private Integer empid;
	private Integer roleid;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	public TEmprole() {
	}

	public TEmprole(Integer id, Integer empid, Integer roleid) {
		this.id = id;
		this.empid = empid;
		this.roleid = roleid;
	}

	public TEmprole(Integer id, Integer empid, Integer roleid, Date createtime, Date updatetime, Integer createperson) {
		this.id = id;
		this.empid = empid;
		this.roleid = roleid;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "empid", nullable = false)
	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	@Column(name = "roleid", nullable = false)
	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
