package com.keeps.model;

// default package
// Generated 2017-6-20 21:33:10 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TEmpclient generated by hbm2java
 */
@Entity
@Table(name = "t_empclient")
public class TEmpclient extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private Integer empid;
	private Integer clientid;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	public TEmpclient() {
	}

	public TEmpclient(Integer empid, Integer clientid) {
		this.empid = empid;
		this.clientid = clientid;
	}

	public TEmpclient(Integer empid, Integer clientid, Date createtime, Date updatetime, Integer createperson) {
		this.empid = empid;
		this.clientid = clientid;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "empid", nullable = false)
	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	@Column(name = "clientid", nullable = false)
	public Integer getClientid() {
		return this.clientid;
	}

	public void setClientid(Integer clientid) {
		this.clientid = clientid;
	}

	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
