package com.keeps.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 2017-6-18 23:15:27 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TEmp generated by hbm2java
 */
@Entity
@Table(name = "t_emp")
public class TEmp extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private Integer orgid;
	private String jobnumber;
	private String name;
	private String email;
	private String phone;
	private String landline;
	private Integer sex;
	private Integer status;
	private String entrydate;
	private String departdate;
	private String birthdate;
	private String solarbirthdate;
	private Integer islunar;
	private String address;
	private String birthplace;
	private String pym;
	private String allpym;
	private String password;
	private Integer isadmin;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;
	
	private String roleids;//该员工所属角色组
	private String rolenames;
	private String orgname;

	public TEmp() {
	}

	public TEmp(Integer id, String jobnumber, String name, String phone, Integer sex, Integer status, Integer islunar, Integer isadmin, String password) {
		this.id = id;
		this.jobnumber = jobnumber;
		this.name = name;
		this.phone = phone;
		this.sex = sex;
		this.status = status;
		this.islunar = islunar;
		this.isadmin = isadmin;
		this.password = password;
	}

	public TEmp(Integer id, Integer orgid, String jobnumber, String name, String email, String phone, String landline, Integer sex, Integer status,
			String entrydate, String departdate, String birthdate, String solarbirthdate, Integer islunar, String address,
			String birthplace, String pym, String allpym, Integer isadmin, String password, Date createtime, Date updatetime, Integer createperson) {
		this.id = id;
		this.orgid = orgid;
		this.jobnumber = jobnumber;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.landline = landline;
		this.sex = sex;
		this.status = status;
		this.entrydate = entrydate;
		this.departdate = departdate;
		this.birthdate = birthdate;
		this.solarbirthdate = solarbirthdate;
		this.islunar = islunar;
		this.address = address;
		this.birthplace = birthplace;
		this.pym = pym;
		this.pym = allpym;
		this.password = password;
		this.isadmin = isadmin;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "orgid", nullable = false)
	public Integer getOrgid() {
		return orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

	@Column(name = "jobnumber", nullable = false, length = 11)
	public String getJobnumber() {
		return this.jobnumber;
	}

	public void setJobnumber(String jobnumber) {
		this.jobnumber = jobnumber;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "landline", length = 20)
	public String getLandline() {
		return this.landline;
	}

	public void setLandline(String landline) {
		this.landline = landline;
	}

	@Column(name = "sex", nullable = false)
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "status", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "entrydate", length = 19)
	public String getEntrydate() {
		return this.entrydate;
	}

	public void setEntrydate(String entrydate) {
		this.entrydate = entrydate;
	}

	@Column(name = "departdate", length = 19)
	public String getDepartdate() {
		return this.departdate;
	}

	public void setDepartdate(String departdate) {
		this.departdate = departdate;
	}

	@Column(name = "birthdate", length = 19)
	public String getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "solarbirthdate", length = 19)
	public String getSolarbirthdate() {
		return this.solarbirthdate;
	}

	public void setSolarbirthdate(String solarbirthdate) {
		this.solarbirthdate = solarbirthdate;
	}

	@Column(name = "islunar", nullable = false)
	public Integer getIslunar() {
		return this.islunar;
	}

	public void setIslunar(Integer islunar) {
		this.islunar = islunar;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "birthplace")
	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	@Column(name = "pym", length = 50)
	public String getPym() {
		return this.pym;
	}

	public void setPym(String pym) {
		this.pym = pym;
	}

	@Column(name = "allpym", length = 50)
	public String getAllpym() {
		return allpym;
	}

	public void setAllpym(String allpym) {
		this.allpym = allpym;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "isadmin", nullable = false)
	public Integer getIsadmin() {
		return isadmin;
	}

	public void setIsadmin(Integer isadmin) {
		this.isadmin = isadmin;
	}

	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

	@Transient
	public String getRoleids() {
		return roleids;
	}

	public void setRoleids(String roleids) {
		this.roleids = roleids;
	}

	@Transient
	public String getRolenames() {
		return rolenames;
	}

	public void setRolenames(String rolenames) {
		this.rolenames = rolenames;
	}

	@Transient
	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	
}
