package com.keeps.model;

// default package
// Generated 2017-7-1 21:23:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TNews generated by hbm2java
 */
@Entity
@Table(name = "t_news")
public class TNews extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private String title;
	private Integer dicttype;
	private String coverimage;
	private String content;
	private String contenttext;
	private Date publishtime;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;
	
	private String empname;
	private String publishtimestr;
	private String dicttypename;
	private String publishtimesta;
	private String publishtimeend;

	public TNews() {
	}

	public TNews(String title, Date publishtime, Date createtime, Date updatetime, int createperson) {
		this.title = title;
		this.publishtime = publishtime;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	public TNews(String title, Integer dicttype, String coverimage, String content, String contenttext,Date publishtime,
			Date createtime, Date updatetime, int createperson) {
		this.title = title;
		this.dicttype = dicttype;
		this.coverimage = coverimage;
		this.content = content;
		this.contenttext = contenttext;
		this.publishtime = publishtime;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "dicttype")
	public Integer getDicttype() {
		return this.dicttype;
	}

	public void setDicttype(Integer dicttype) {
		this.dicttype = dicttype;
	}

	@Column(name = "coverimage", length = 40)
	public String getCoverimage() {
		return this.coverimage;
	}

	public void setCoverimage(String coverimage) {
		this.coverimage = coverimage;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "contenttext")
	public String getContenttext() {
		return this.contenttext;
	}

	public void setContenttext(String contenttext) {
		this.contenttext = contenttext;
	}

	@Column(name = "publishtime", nullable = false, length = 19)
	public Date getPublishtime() {
		return publishtime;
	}

	public void setPublishtime(Date publishtime) {
		this.publishtime = publishtime;
	}
	
	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", nullable = false, length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson", nullable = false)
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

	@Transient
	public String getDicttypename() {
		return dicttypename;
	}

	public void setDicttypename(String dicttypename) {
		this.dicttypename = dicttypename;
	}

	@Transient
	public String getPublishtimesta() {
		return publishtimesta;
	}

	public void setPublishtimesta(String publishtimesta) {
		this.publishtimesta = publishtimesta;
	}

	@Transient
	public String getPublishtimeend() {
		return publishtimeend;
	}

	public void setPublishtimeend(String publishtimeend) {
		this.publishtimeend = publishtimeend;
	}

	@Transient
	public String getPublishtimestr() {
		return publishtimestr;
	}

	public void setPublishtimestr(String publishtimestr) {
		this.publishtimestr = publishtimestr;
	}

	@Transient
	public String getEmpname() {
		return empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	
}
