package com.keeps.model;

// default package
// Generated 2017-6-20 15:17:02 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.keeps.core.model.AbstractModelInteger;

/**
 * TOperateAccess generated by hbm2java
 */
@Entity
@Table(name = "t_operate_access")
public class TOperateAccess extends AbstractModelInteger implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Integer type;
	private Integer relid;
	private Integer operateid;

	public TOperateAccess() {
	}

	public TOperateAccess(Integer type, Integer relid, Integer operateid) {
		this.type = type;
		this.relid = relid;
		this.operateid = operateid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "relid", nullable = false)
	public Integer getRelid() {
		return this.relid;
	}

	public void setRelid(Integer relid) {
		this.relid = relid;
	}

	@Column(name = "operateid", nullable = false)
	public Integer getOperateid() {
		return this.operateid;
	}

	public void setOperateid(Integer operateid) {
		this.operateid = operateid;
	}

}
