package com.keeps.model;
// default package
// Generated 2017-6-18 13:49:40 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TOrg generated by hbm2java
 */
@Entity
@Table(name = "t_org")
public class TOrg extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private String name;
	private Integer pid;
	private String pname;
	private String fullpid;
	private String fullpname;
	private Integer orgtype;
	private Integer sort;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	public TOrg() {
	}

	public TOrg(String name, Integer pid, String pname, Integer orgtype, Integer sort) {
		this.name = name;
		this.pid = pid;
		this.pname = pname;
		this.orgtype = orgtype;
		this.sort = sort;
	}

	public TOrg(String name, Integer pid, String pname, String fullpid, String fullpname, Integer orgtype, Integer sort, Date createtime, Date updatetime,
			Integer createperson) {
		this.name = name;
		this.pid = pid;
		this.pname = pname;
		this.fullpid = fullpid;
		this.fullpname = fullpname;
		this.orgtype = orgtype;
		this.sort = sort;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pid", nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "pname", nullable = false)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "fullpid")
	public String getFullpid() {
		return fullpid;
	}

	public void setFullpid(String fullpid) {
		this.fullpid = fullpid;
	}

	@Column(name = "fullpname")
	public String getFullpname() {
		return fullpname;
	}

	public void setFullpname(String fullpname) {
		this.fullpname = fullpname;
	}

	@Column(name = "orgtype", nullable = false)
	public Integer getOrgtype() {
		return this.orgtype;
	}

	public void setOrgtype(Integer orgtype) {
		this.orgtype = orgtype;
	}

	@Column(name = "sort", nullable = false)
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

}
