package com.keeps.model;

// default package
// Generated 2017-7-1 23:35:48 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * TSchedule generated by hbm2java
 */
@Entity
@Table(name = "t_schedule")
public class TSchedule extends AbstractModelInteger implements ModelPlusSchool{

	private Integer id;
	private String title;
	private String remark;
	private Integer level;
	private Integer status;
	private Date scheduletime;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;

	private String scheduletimestr;
	private String scheduletimesta;
	private String scheduletimeend;
	public TSchedule() {
	}

	public TSchedule(Date scheduletime, Date createtime, Date updatetime, int createperson) {
		this.scheduletime = scheduletime;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	public TSchedule(String title, String remark, Integer level, Integer status, Date scheduletime, Date createtime,
			Date updatetime, int createperson) {
		this.title = title;
		this.remark = remark;
		this.level = level;
		this.status = status;
		this.scheduletime = scheduletime;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "remark", length = 1000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduletime", nullable = false, length = 19)
	public Date getScheduletime() {
		return this.scheduletime;
	}

	public void setScheduletime(Date scheduletime) {
		this.scheduletime = scheduletime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", nullable = false, length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson", nullable = false)
	public Integer getCreateperson() {
		return this.createperson;
	}
	
	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}

	@Transient
	public String getScheduletimestr() {
		return scheduletimestr;
	}

	public void setScheduletimestr(String scheduletimestr) {
		this.scheduletimestr = scheduletimestr;
	}

	@Transient
	public String getScheduletimesta() {
		return scheduletimesta;
	}

	public void setScheduletimesta(String scheduletimesta) {
		this.scheduletimesta = scheduletimesta;
	}

	@Transient
	public String getScheduletimeend() {
		return scheduletimeend;
	}

	public void setScheduletimeend(String scheduletimeend) {
		this.scheduletimeend = scheduletimeend;
	}

}
