package com.keeps.model;

// default package
// Generated 2017-1-11 10:08:53 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.keeps.core.model.AbstractModel;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user")
public class TUser extends AbstractModel implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String nickname;
	private String email;
	private Integer phone;
	private String password;
	private Integer status;
	private Date createtime;
	private Date updatetime;

	public TUser() {
	}

	public TUser(String password, Integer status) {
		this.password = password;
		this.status = status;
	}

	public TUser(String nickname, String email, Integer phone, String password, Integer status, Date createtime,
			Date updatetime) {
		this.nickname = nickname;
		this.email = email;
		this.phone = phone;
		this.password = password;
		this.status = status;
		this.createtime = createtime;
		this.updatetime = updatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nickname", length = 80)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false)
	public Integer isStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

}
