package com.keeps.ksxtmanager.model;

// default package
// Generated 2017-9-17 11:39:11 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * KsQuestions generated by hbm2java
 */
@Entity
@Table(name = "ks_questions")
public class KsQuestions extends AbstractModelInteger implements ModelPlusSchool {

	private Integer id;
	private String title;
	private Integer degofdifftype;
	private Integer questionstype;
	private Integer problemtype;
	private String answeroption;
	private String correctanswer;
	private Integer isatuoscoring;
	private Integer examnum;
	private Integer correctnum;
	private Integer errornum;
	private String remark;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;
	private String degofdifftypename;
	private String questionstypename;
	private String problemtypename;
	public KsQuestions() {
	}

	public KsQuestions(String title, Integer degofdifftype, Integer questionstype, Integer problemtype, String answeroption, Integer isatuoscoring,
			Integer examnum, Integer correctnum, Integer errornum, Date createtime, Date updatetime, Integer createperson) {
		this.title = title;
		this.degofdifftype = degofdifftype;
		this.questionstype = questionstype;
		this.problemtype = problemtype;
		this.answeroption = answeroption;
		this.isatuoscoring = isatuoscoring;
		this.examnum = examnum;
		this.correctnum = correctnum;
		this.errornum = errornum;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	public KsQuestions(String title, Integer degofdifftype, Integer questionstype, Integer problemtype, String answeroption, String correctanswer,
			Integer isatuoscoring, Integer examnum, Integer correctnum, Integer errornum, String remark, Date createtime,
			Date updatetime, Integer createperson) {
		this.title = title;
		this.degofdifftype = degofdifftype;
		this.questionstype = questionstype;
		this.problemtype = problemtype;
		this.answeroption = answeroption;
		this.correctanswer = correctanswer;
		this.isatuoscoring = isatuoscoring;
		this.examnum = examnum;
		this.correctnum = correctnum;
		this.errornum = errornum;
		this.remark = remark;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 1024)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	@Column(name = "degofdifftype", nullable = false)
	public Integer getDegofdifftype() {
		return degofdifftype;
	}

	public void setDegofdifftype(Integer degofdifftype) {
		this.degofdifftype = degofdifftype;
	}

	@Column(name = "questionstype", nullable = false)
	public Integer getQuestionstype() {
		return this.questionstype;
	}

	public void setQuestionstype(Integer questionstype) {
		this.questionstype = questionstype;
	}

	@Column(name = "problemtype", nullable = false)
	public Integer getProblemtype() {
		return this.problemtype;
	}

	public void setProblemtype(Integer problemtype) {
		this.problemtype = problemtype;
	}

	@Column(name = "answeroption", nullable = false, length = 5000)
	public String getAnsweroption() {
		return this.answeroption;
	}

	public void setAnsweroption(String answeroption) {
		this.answeroption = answeroption;
	}

	@Column(name = "correctanswer", length = 5000)
	public String getCorrectanswer() {
		return this.correctanswer;
	}

	public void setCorrectanswer(String correctanswer) {
		this.correctanswer = correctanswer;
	}

	@Column(name = "isatuoscoring")
	public Integer getIsatuoscoring() {
		return this.isatuoscoring;
	}

	public void setIsatuoscoring(Integer isatuoscoring) {
		this.isatuoscoring = isatuoscoring;
	}

	@Column(name = "examnum")
	public Integer getExamnum() {
		return this.examnum;
	}

	public void setExamnum(Integer examnum) {
		this.examnum = examnum;
	}

	@Column(name = "correctnum")
	public Integer getCorrectnum() {
		return this.correctnum;
	}

	public void setCorrectnum(Integer correctnum) {
		this.correctnum = correctnum;
	}

	@Column(name = "errornum")
	public Integer getErrornum() {
		return this.errornum;
	}

	public void setErrornum(Integer errornum) {
		this.errornum = errornum;
	}

	@Column(name = "remark", length = 1024)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "createtime")
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime")
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson")
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}
	@Transient
	public String getDegofdifftypename() {
		return degofdifftypename;
	}

	public void setDegofdifftypename(String degofdifftypename) {
		this.degofdifftypename = degofdifftypename;
	}
	
	@Transient
	public String getQuestionstypename() {
		return questionstypename;
	}

	
	public void setQuestionstypename(String questionstypename) {
		this.questionstypename = questionstypename;
	}

	@Transient
	public String getProblemtypename() {
		return problemtypename;
	}

	public void setProblemtypename(String problemtypename) {
		this.problemtypename = problemtypename;
	}

}
