package com.keeps.ksxtmanager.model;
// default package
// Generated 2017-10-5 16:25:39 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.keeps.core.model.AbstractModelInteger;
import com.keeps.core.model.plus.ModelPlusSchool;

/**
 * KsShijuan generated by hbm2java
 */
@Entity
@Table(name = "ks_shijuan")
public class KsShijuan extends AbstractModelInteger implements ModelPlusSchool {

	private Integer id;
	private String title;
	private Integer shijuantype;
	private Integer degofdifftype;
	private Date starttime;
	private Date endtime;
	private Integer timelength;
	private Integer kaoshitype;
	private String remark;
	private Integer zongfen;
	private String orgids;
	private String empids;
	private Integer status;
	private Date createtime;
	private Date updatetime;
	private Integer createperson;
	private String empname;

	private Integer empid;
	private Integer orgid;
	private String questionsids;
	private String starttimestr;
	private String endtimestr;
	private String degofdifftypename;
	private String shijuantypename;
	public KsShijuan() {
	}

	public KsShijuan(Integer id, String title, Integer shijuantype, Integer degofdifftype, Integer kaoshitype, String remark,
			Integer zongfen, Integer status, Date createtime, Date updatetime, Integer createperson) {
		this.id = id;
		this.title = title;
		this.shijuantype = shijuantype;
		this.degofdifftype = degofdifftype;
		this.kaoshitype = kaoshitype;
		this.remark = remark;
		this.zongfen = zongfen; 
		this.status = status;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	public KsShijuan(Integer id, String title, Integer shijuantype, Integer degofdifftype, Date starttime, Date endtime,
			Integer timelength, Integer kaoshitype, String remark,
			Integer zongfen, Integer status, Date createtime, Date updatetime, Integer createperson) {
		this.id = id;
		this.title = title;
		this.shijuantype = shijuantype;
		this.degofdifftype = degofdifftype;
		this.starttime = starttime;
		this.endtime = endtime;
		this.timelength = timelength;
		this.kaoshitype = kaoshitype;
		this.remark = remark;
		this.zongfen = zongfen; 
		this.status = status;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createperson = createperson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "shijuantype", nullable = false)
	public Integer getShijuantype() {
		return this.shijuantype;
	}

	public void setShijuantype(Integer shijuantype) {
		this.shijuantype = shijuantype;
	}

	@Column(name = "degofdifftype", nullable = false)
	public Integer getDegofdifftype() {
		return this.degofdifftype;
	}

	public void setDegofdifftype(Integer degofdifftype) {
		this.degofdifftype = degofdifftype;
	}

	@Column(name = "starttime", length = 19)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Column(name = "endtime", length = 19)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "timelength")
	public Integer getTimelength() {
		return this.timelength;
	}

	public void setTimelength(Integer timelength) {
		this.timelength = timelength;
	}

	@Column(name = "kaoshitype", nullable = false)
	public Integer getKaoshitype() {
		return this.kaoshitype;
	}

	public void setKaoshitype(Integer kaoshitype) {
		this.kaoshitype = kaoshitype;
	}

	@Column(name = "remark", length = 1024)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "zongfen")
	public Integer getZongfen() {
		return zongfen;
	}

	public void setZongfen(Integer zongfen) {
		this.zongfen = zongfen;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "updatetime", nullable = false, length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "createperson", nullable = false)
	public Integer getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(Integer createperson) {
		this.createperson = createperson;
	}
	
	@Transient
	public String getDegofdifftypename() {
		return degofdifftypename;
	}

	public void setDegofdifftypename(String degofdifftypename) {
		this.degofdifftypename = degofdifftypename;
	}

	@Transient
	public String getShijuantypename() {
		return shijuantypename;
	}

	public void setShijuantypename(String shijuantypename) {
		this.shijuantypename = shijuantypename;
	}

	@Transient
	public String getStarttimestr() {
		return starttimestr;
	}

	public void setStarttimestr(String starttimestr) {
		this.starttimestr = starttimestr;
	}

	@Transient
	public String getEndtimestr() {
		return endtimestr;
	}

	public void setEndtimestr(String endtimestr) {
		this.endtimestr = endtimestr;
	}

	@Column(name = "orgids")
	public String getOrgids() {
		return orgids;
	}

	public void setOrgids(String orgids) {
		this.orgids = orgids;
	}

	@Column(name = "empids")
	public String getEmpids() {
		return empids;
	}

	public void setEmpids(String empids) {
		this.empids = empids;
	}

	@Column(name = "questionsids", nullable = false)
	public String getQuestionsids() {
		return questionsids;
	}

	public void setQuestionsids(String questionsids) {
		this.questionsids = questionsids;
	}
	
	@Transient
	public String getEmpname() {
		return empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	@Transient
	public Integer getEmpid() {
		return empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	@Transient
	public Integer getOrgid() {
		return orgid;
	}

	public void setOrgid(Integer orgid) {
		this.orgid = orgid;
	}

}
